### ISSUE TITLE
Hidden Tools menu item

### ISSUE THREAD

**Issue by ferencsarai** [leecade/caniuse_local#3]
Ubuntu 14.04, Sublime Text 2:

Reloading plugin /home/fsarai/.config/sublime-text-2/Packages/caniuse/v8.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./v8.py", line 11, in <module>
    import SublimeJS.loader.pyv8loader as pyv8loader
ImportError: No module named SublimeJS.loader.pyv8loader

**Comment by leecade** [comment]
sorry for that, https://github.com/leecade/caniuse/issues/2 may help you

**Comment by LOQUILLO** [comment]
Fixed name but caniuse isn't working, don't show nothing in status bar.
ST2 was restarted and working but isn't supporting continuos check or test of terms.
first, second,...fifth all ok, in sixth time dont show nothing, it's necessary wait for continue again.

**Comment by leecade** [comment]
@LOQUILLO ok, I will try and fix it.

**Comment by LOQUILLO** [comment]
Installed the last versión minutes ago and isn't working, selected term, Tools - and "Caniuse" is inactive or greyed.

**Comment by leecade** [comment]
@LOQUILLO the latest version is v0.1.6.

If not working, try:
1. after install restart ST
2. create a new file and try again
3. still not working, tell me again, thanks

Apology for try very early version.

**Comment by juvenrui** [comment]
remove 0.1.3, and reinstall 0.1.6, but not working, again more.....

**Comment by ice8lue** [comment]
I just installed the latest version on ST3, OSX. It's working for me exactly one time. After the caniuse sentence is in the statusbar, it is not being overwritten by another.

**Comment by LOQUILLO** [comment]
Hi @ice8lue it's like a delay, right, new versión dont fix this problem.

**Comment by leecade** [comment]
So far, everyone's working fine?

I noticed two problems:
1. sometime status bar can not being overwritten
2. status bar info can not hold on a fixed time

This week end I will go on fix it, add user settings to specify browsers:

`iOS Safari` `Opera Mini`  `Android Browser`    `Blackberry Browser` `IE Mobile`

@Juvencn @LOQUILLO @ice8lue

**Comment by nandorocker** [comment]
I installed it and restarted ST, menu item is greyed out and the shortcut won't work.

**Comment by LOQUILLO** [comment]
It isn't fixed, I'am too waiting for a new version.

**Comment by leecade** [comment]
This plugin require pyv8, if auto installed failed try [Manual installation](https://github.com/emmetio/pyv8-binaries#manual-installation)

and load issue see https://github.com/sergeche/emmet-sublime/issues/129

**Comment by LOQUILLO** [comment]
I had installed pyv8 manually but nothing has changed, there are the error, dont show nothing in status bar, had uninstalled caniuselocal, reinstalled and nothing. Isn't working.
